; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit NeoPixel@^1.10.0

; ATMEGA8A
[env:ATmega8]
extends = common
platform = atmelavr
board = ATmega8
build_flags = -DF_CPU=16000000UL

; ATmega48
;[env:ATmega48]
;extends = common
;platform = atmelavr
;board = ATmega48
;build_flags = -DF_CPU=16000000UL

; ATmega88
[env:ATmega88]
extends = common
platform = atmelavr
board = ATmega88
build_flags = -DF_CPU=16000000UL

; ATmega168	
[env:ATmega168]
extends = common
platform = atmelavr
board = ATmega168
build_flags = -DF_CPU=16000000UL

; ATMEGA328P (Arduino Uno, Nano)
[env:ATmega328P]
extends = common
platform = atmelavr
board = ATmega328P
build_flags = -DF_CPU=16000000UL

; ATTINY85
[env:ATTINY85]
extends = common
platform = atmelavr
board = ATTINY85
build_flags = -DF_CPU=16000000UL

; ESP8266
[env:esp8266]
extends = common
platform = espressif8266
board = esp01_1m

; ESP32
[env:esp32]
extends = common
platform = espressif32
board = esp32dev

